<em>We'll start off by importing numpy and the linear algebra class (linalg) from numpy</em>

In [2]:
import numpy as np
import numpy.linalg as npla

*Let's go back to the Ax = b setup*

In [3]:
A = np.array([[ 2. ,  7. ,  1. ,  8. ],
       [ 1. ,  5.5,  8.5,  5. ],
       [ 0. ,  1. , 12. ,  2.5],
       [-1. , -4.5, -4.5,  3.5]])
print("A:", A,'\n')

A: [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]] 



In [4]:
# Recall we found U and L
# We used Gaussian elimination on the blackboard to triangularize A, giving U
# During Gaussian elimination, we wrote down the multipliers in a lower triangular array 
# I and then put ones on the diagonal, giving L

U = np.array([[2,7,1,8],[0,2,8,1],[0,0,8,2],[0,0,0,8]])
L = np.array([[1,0,0,0],[.5,1,0,0],[0,.5,1,0],[-.5,-.5,0,1]])
print(U, "\n\n", L)

[[2 7 1 8]
 [0 2 8 1]
 [0 0 8 2]
 [0 0 0 8]] 

 [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.   0.5  1.   0. ]
 [-0.5 -0.5  0.   1. ]]


In [5]:
# The theorem: Gaussian elimination factors A as the product L time U

print( L @ U)
print()
print(A)

[[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]

[[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]


In [7]:
def LUfactorNoPiv(A):
    """Factor a square matrix, A == L @ U (no partial pivoting)
    Parameters: 
      A: the matrix.
    Outputs (in order):
      L: the lower triangular factor, same dimensions as A, with ones on the diagonal
      U: the upper triangular factor, same dimensions as A
    """
    
    # Check the input
    m, n = A.shape
    assert m == n, 'input matrix A must be square'
    
    # Make a copy of the matrix that we will transform into L and U
    LU = A.astype(np.float64).copy()
    
    # Eliminate each column in turn
    for piv_col in range(n):
            
        # Update the rest of the matrix
        pivot = LU[piv_col, piv_col]
        assert pivot != 0., "pivot is zero, can't continue"
        for row in range(piv_col + 1, n):
            multiplier = LU[row, piv_col] / pivot
            LU[row, piv_col] = multiplier
            LU[row, (piv_col+1):] -= multiplier * LU[piv_col, (piv_col+1):]
            
    # Separate L and U in the result
    #print("LU:\n", LU)
    U = np.triu(LU)
    L = LU - U + np.eye(n)
    
    return (L, U)

In [9]:
A = np.array([[1, 2, 3], [1,1,1], [-1,1,2]])
L,U = LUfactorNoPiv(A)
print("\nA\n", A, "\n\nL\n", L, "\n\nU\n", U)


A
 [[ 1  2  3]
 [ 1  1  1]
 [-1  1  2]] 

L
 [[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-1. -3.  1.]] 

U
 [[ 1.  2.  3.]
 [ 0. -1. -2.]
 [ 0.  0. -1.]]


*Using the fact that, Ax = b means LUx = b:*

In [12]:
def Lsolve(L, b):
    """Forward solve a unit lower triangular system Ly = b for y
    Parameters: 
      L: the matrix, must be square, lower triangular, with ones on the diagonal
      b: the right-hand side vector
    Output:
      y: the solution vector to L @ y == b
    """
    
    # Check the input
    m, n = L.shape
    assert m == n, "matrix L must be square"
    assert np.all(np.tril(L) == L), "matrix L must be lower triangular"
    assert np.all(np.diag(L) == 1), "matrix L must have ones on the diagonal"
    
    # Make a copy of b that we will transform into the solution
    y = b.astype(np.float64).copy()
    
    # Forward solve
    for col in range(n):
        y[col+1:] -= y[col] * L[col+1:, col]
        
    return y

In [13]:
def Usolve(U, y):
    """Backward solve an upper triangular system Ux = y for x
    Parameters: 
      U: the matrix, must be square, upper triangular, with nonzeros on the diagonal
      y: the right-hand side vector
    Output:
      x: the solution vector to U @ x == y
    """
    
    print("\nyou will write Usolve in hw2\n")
    
    return 

*Testing it out...*

In [14]:
A = np.array([[ 2. ,  7. ,  1. ,  8. ],
       [ 1. ,  5.5,  8.5,  5. ],
       [ 0. ,  1. , 12. ,  2.5],
       [-1. , -4.5, -4.5,  3.5]])

L, U = LUfactorNoPiv(A)
b = np.array([1, 2, 3, 4])

y = Lsolve(L,b)
print("Ran Lsolve(L,b) and got y:\n", y)

x = Usolve(U,y)
print("Ran Usolve(U,y) and got x:\n", x)

print("\nA@x:", A@x)
print("\nresidual norm:", npla.norm(b - A @ x))

Ran Lsolve(L,b) and got y:
 [1.   1.5  2.25 5.25]

you will write Usolve in hw2

Ran Usolve(U,y) and got x:
 None


TypeError: Object arrays are not currently supported

*Back to our **LUfactorNoPiv()** function...*

In [15]:
# But LU factorization (without pivoting) fails if it encounters a zero pivot

A = np.array([[0, 1], [1, 2]])
L,U = LUfactorNoPiv(A)

AssertionError: pivot is zero, can't continue

In [17]:
def LUfactor(A, pivoting = True):
    """Factor a square matrix with partial pivoting, A[p,:] == L @ U
    Parameters: 
      A: the matrix.
      pivoting: whether or not to do partial pivoting
    Outputs (in order):
      L: the lower triangular factor, same dimensions as A, with ones on the diagonal
      U: the upper triangular factor, same dimensions as A
      p: the permutation vector that permutes the rows of A by partial pivoting
    """
    
    # Check the input
    m, n = A.shape
    assert m == n, 'input matrix A must be square'
    
    # Initialize p to be the identity permutation
    p = np.array(range(n))
    
    # Make a copy of the matrix that we will transform into L and U
    LU = A.astype(np.float64).copy()
    
    # Eliminate each column in turn
    for piv_col in range(n):
        
        # Choose the pivot row and swap it into place
        if pivoting:
            piv_row = piv_col + np.argmax(LU[piv_col:, piv_col]) 
            assert LU[piv_row, piv_col] != 0., "can't find nonzero pivot, matrix is singular"
            LU[[piv_col, piv_row], :]  = LU[[piv_row, piv_col], :]
            p[[piv_col, piv_row]]      = p[[piv_row, piv_col]]
            
        # Update the rest of the matrix
        pivot = LU[piv_col, piv_col]
        assert pivot != 0., "pivot is zero, can't continue"
        for row in range(piv_col + 1, n):
            multiplier = LU[row, piv_col] / pivot
            LU[row, piv_col] = multiplier
            LU[row, (piv_col+1):] -= multiplier * LU[piv_col, (piv_col+1):]
            
    # Separate L and U in the result
    U = np.triu(LU)
    L = LU - U + np.eye(n)
    
    return (L, U, p)

*Testing out our **LUfactor()** function with our counter example that failed the previous function...*

In [18]:
# Our 2-by-2 counter-example again

print('A:\n', A)
L, U, p = LUfactor(A)
print('\nL:\n', L)
print('\nU:\n', U)
print('\np: ', p)

A:
 [[0 1]
 [1 2]]

L:
 [[1. 0.]
 [0. 1.]]

U:
 [[1. 2.]
 [0. 1.]]

p:  [1 0]


In [103]:
# Other examples!
A = np.round(20*np.random.rand(5,5))

print('A:\n', A)
L, U, p = LUfactor(A)
print('\nL:\n', L)
print('\nU:\n', U)
print('\np: ', p)

A:
 [[ 7. 10.  7.  6. 15.]
 [11. 17. 18.  1.  8.]
 [18.  4. 12. 11. 14.]
 [ 3. 16. 11. 18.  0.]
 [ 7. 12.  9. 13. 18.]]

L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.          0.        ]
 [ 0.61111111  0.94927536  1.          0.          0.        ]
 [ 0.38888889  0.68115942 -0.84641638  1.          0.        ]
 [ 0.38888889  0.55072464 -1.23549488  1.65044098  1.        ]]

U:
 [[ 18.           4.          12.          11.          14.        ]
 [  0.          15.33333333   9.          16.16666667  -2.33333333]
 [  0.           0.           2.12318841 -21.06884058   1.65942029]
 [  0.           0.           0.         -20.12286689  15.54948805]
 [  0.           0.           0.           0.         -12.77272727]]

p:  [2 3 1 4 0]


In [105]:
# Do it again with the no-pivot function,
# but use the p matrix we found to our advantage:

p = [1, 0]
A = np.array([[0, 1], [1, 2]])

L, U = LUfactorNoPiv(A[p])
print('\nA[p]:\n', A[p])
print('\nL:\n', L)
print('\nU:\n', U)


A[p]:
 [[1 2]
 [0 1]]

L:
 [[1. 0.]
 [0. 1.]]

U:
 [[1. 2.]
 [0. 1.]]


In [106]:
# A larger example of LU with partial pivoting

A = np.round(20*np.random.rand(5,5))
print('matrix A:\n', A)
xorig = np.round(10*np.random.rand(5))
print('\noriginal x:', xorig)
b = A @ xorig
print('\nright-hand side b:', b)

matrix A:
 [[ 2. 16. 10. 16. 17.]
 [17. 15. 15. 18.  3.]
 [13. 14.  3.  8.  2.]
 [20.  2. 11. 10. 16.]
 [19.  5.  2. 12. 11.]]

original x: [1. 8. 6. 4. 6.]

right-hand side b: [356. 317. 187. 238. 185.]


In [107]:
# Factor the larger example

L, U, p = LUfactor(A)
print(L,"\n\n",U,"\n\n",p,"\n")
print("norm of difference between L times U and permuted A:", npla.norm( L@U - A[p,:]))

[[1.         0.         0.         0.         0.        ]
 [0.1        1.         0.         0.         0.        ]
 [0.85       0.84177215 1.         0.         0.        ]
 [0.95       0.19620253 5.53608247 1.         0.        ]
 [0.65       0.80379747 6.13745704 0.51181744 1.        ]] 

 [[ 20.           2.          11.          10.          16.        ]
 [  0.          15.8          8.9         15.          15.4       ]
 [  0.           0.          -1.84177215  -3.12658228 -23.56329114]
 [  0.           0.           0.          16.86597938 123.22680412]
 [  0.           0.           0.           0.          60.77057865]] 

 [3 0 1 4 2] 

norm of difference between L times U and permuted A: 4.7207330545682824e-15


In [108]:
# Solve with the larger example

y = Lsolve(L,b[p])
print("y:", y)
x = Usolve(U,y)
print("\nx:", x)
print("\nresidual norm:", npla.norm(b - A @ x))

y: [ 238.          332.2        -164.93670886  806.82474227  364.62347188]

you will write Usolve in hw2


x: None


TypeError: Object arrays are not currently supported

*Cholesky Factorization*

In [109]:
# The example I had on the slides in class:
C = np.array([[4,-1],[-1,3]])

# Let's make sure that it IS a symmetrical matrix visually!
print(C,"\n\n",C.T,"\n")

# Run Cholesky on the matrix
L = npla.cholesky(C)
print(L,"\n")

# Check that L is indeed a solution!
print(L @ L.T)
print("\nresidual norm:", npla.norm(C - L @ L.T))

[[ 4 -1]
 [-1  3]] 

 [[ 4 -1]
 [-1  3]] 

[[ 2.         0.       ]
 [-0.5        1.6583124]] 

[[ 4. -1.]
 [-1.  3.]]

residual norm: 0.0


*Another one!*

In [111]:
# Another Cholesky example!
C = np.array([[7,3,7,3,7],[3,7,3,7,3],[7,3,7,3,7],[3,7,3,7,3],[7,3,7,3,7]])

# Let's make sure that it IS a symmetrical matrix visually!
print(C,"\n\n",C.T,"\n")

# Run Cholesky on the matrix
L = npla.cholesky(C)
print(L,"\n")

# Check that L is indeed a solution!
print(L @ L.T)
print("\nresidual norm:", npla.norm(C - L @ L.T))

[[7 3 7 3 7]
 [3 7 3 7 3]
 [7 3 7 3 7]
 [3 7 3 7 3]
 [7 3 7 3 7]] 

 [[7 3 7 3 7]
 [3 7 3 7 3]
 [7 3 7 3 7]
 [3 7 3 7 3]
 [7 3 7 3 7]] 



LinAlgError: Matrix is not positive definite