This is the simplest (naive approach) matrix multiplication algorithm:

Input: matrices A and B
Let C be a new matrix of the appropriate size
For i from 1 to n:
    For j from 1 to p:
        Let sum = 0
        For k from 1 to m:
            Set sum ← sum + Aik × Bkj
        Set Cij ← sum
Return C

In [1]:
import numpy as np
import numpy.linalg as npla

In [2]:
# We're only going to implement it to multiply 2 square nxn matrices
def mm(A, B, n):
    C = np.empty([n,n])
    for i in range(n):
        for j in range(n):
            sum = 0
            for k in range(n):
                sum += A[i,k]*B[k,j]
            C[i,j] = sum
    return C


In [4]:
# Test it out

n = 10
A = np.array(range(n**2)).reshape(n,n)
B = np.array(range(n**2, 2*n**2)).reshape(n,n)

X = A@B
Y = mm(A,B,n)
print("A:\n",A,"\nB:\n",B)
print("\nUsing numpy's @:\n",X,"\n\nUsing our mm(A,B,n):\n",Y)
print("\nresidual norm:", npla.norm(Y - X))

A:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 
B:
 [[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]

Using numpy's @:
 [[  7350   7395   7440   7485   7530   7575   7620   7665   7710   7755]
 [ 21850  21995  22140  22285  22430  22575  22720  22865  23010  23155]
 [ 36350  36595  36840  37085  37330  37575  37820  38065  38310