<em>We'll start off by importing numpy and the linear algebra class (linalg) from numpy</em>

In [2]:
import numpy as np
import numpy.linalg as npla

*Demonstrating some "special" matrices*

In [3]:
A = np.array(range(25)).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
print(A@I)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


*Demonstrating how to create a diagonal matrix and transposed matrices*

In [8]:
D = np.diag([2,1,1,0,3])

In [9]:
print("A =\n", A,"\n\n D =\n", D)

A =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

 D =
 [[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 3]]


In [10]:
print("A.D =\n",A@D, "\n\n D.A =\n",D@A, "\n\n (D.A)Transposed =\n",(D@A).T)

A.D =
 [[ 0  1  2  0 12]
 [10  6  7  0 27]
 [20 11 12  0 42]
 [30 16 17  0 57]
 [40 21 22  0 72]] 

 D.A =
 [[ 0  2  4  6  8]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  0  0  0  0]
 [60 63 66 69 72]] 

 (D.A)Transposed =
 [[ 0  5 10  0 60]
 [ 2  6 11  0 63]
 [ 4  7 12  0 66]
 [ 6  8 13  0 69]
 [ 8  9 14  0 72]]


*Demonstrating how to change single matrix cell entries and single row entries*

In [11]:
A[0,0] = 42
A[2,2] = 99
print(A)

[[42  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 99 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
print(A[4,:])

[20 21 22 23 24]


*Demonstrating how to change the row order in a matrix*

In [16]:
B = A[[1,0,2,3,4],:]
print(A, "\n\n", B)

[[42  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 99 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

 [[ 5  6  7  8  9]
 [42  1  2  3  4]
 [10 11 99 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


*Demonstrating the .permutation() function and its use in rearraning row order in a matrix*

In [40]:
np.random.permutation(5)

array([3, 1, 0, 2, 4])

In [41]:
vec = np.random.permutation(5)
I = np.eye(5)

print(vec, "\n")
P = I[vec,:]
print(P)

[1 3 4 2 0] 

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [42]:
print(P @ A, '\n')
print(P @ A.T, '\n')
print((P @ A).T, '\n')

[[ 5.  6.  7.  8.  9.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [10. 11. 99. 13. 14.]
 [42.  1.  2.  3.  4.]] 

[[ 1.  6. 11. 16. 21.]
 [ 3.  8. 13. 18. 23.]
 [ 4.  9. 14. 19. 24.]
 [ 2.  7. 99. 17. 22.]
 [42.  5. 10. 15. 20.]] 

[[ 5. 15. 20. 10. 42.]
 [ 6. 16. 21. 11.  1.]
 [ 7. 17. 22. 99.  2.]
 [ 8. 18. 23. 13.  3.]
 [ 9. 19. 24. 14.  4.]] 



*Reordering rows vs. reordering columns*

In [44]:
vec = [3,1,2,4,0]
print("A:\n", A, "\n\nvec:\n", vec)

A:
 [[42  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 99 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

vec:
 [3, 1, 2, 4, 0]


In [45]:
print("A[vec,:]\n", A[vec,:], "\n\nA[:,vec]\n", A[:,vec])

A[vec,:]
 [[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 99 13 14]
 [20 21 22 23 24]
 [42  1  2  3  4]] 

A[:,vec]
 [[ 3  1  2  4 42]
 [ 8  6  7  9  5]
 [13 11 99 14 10]
 [18 16 17 19 15]
 [23 21 22 24 20]]


*Let's go back to the Ax = b setup*

In [ ]:
A = np.array([[ 2. ,  7. ,  1. ,  8. ],
       [ 1. ,  5.5,  8.5,  5. ],
       [ 0. ,  1. , 12. ,  2.5],
       [-1. , -4.5, -4.5,  3.5]])
print("A:", A,'\n')

In [ ]:
# Recall we found U and L
# We used Gaussian elimination on the blackboard to triangularize A, giving U
# During Gaussian elimination, we wrote down the multipliers in a lower triangular array 
# I and then put ones on the diagonal, giving L

U = np.array([[2,7,1,8],[0,2,8,1],[0,0,8,2],[0,0,0,8]])
L = np.array([[1,0,0,0],[.5,1,0,0],[0,.5,1,0],[-.5,-.5,0,1]])
print(U, "\n\n", L)

In [ ]:
# The theorem: Gaussian elimination factors A as the product L time U

print( L @ U)
print()
print(A)